name: Java with Nexus Repository

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Step 2 - Download zip file to ear directory
      run: |
          wget localhost:8082/repository/maven-releases/Nexus_zip/Nexus_zip/1.0.1/Nexus_zip-1.0.1.zip

    - name: Step 3 - Build with Ant Project
      run: |
          ant -noinput -buildfile build.xml
   
