name: Java build with ant
on:
  push:
    branches:
      - GitHub_Action_Testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from Github
        uses: actions/checkout@v2
        
      - name: Step 2 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Step 3 - copying the files to ear
        run: |
          ROOT_PATH=$PWD
          cd ear/workbrain
          ls -a
          cp $ROOT_PATH/ear_work2/*.war .
          echo "after copy war file and jarfile"
          cp -R $ROOT_PATH/ear_work1/* .
          rm testdelete.txt
          cd ..
          zip -r workbrain.zip $ROOT_PATH/ear/workbrain/*
          mkdir unzip
          unzip -d ear/unzip workbrain.zip
          ls -a
          cd $ROOT_PATH/ear/unzip
          ls -a
