name: Java ant build

on:
  push:
    branches:
      - GitHub_Action_Testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from Github
        uses: actions/checkout@v2
      
      - name: Step 2 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Step 3 - Build with Ant Project
        run: |
          ant -noinput -buildfile build.xml
          mkdir staging && cp build/jar/*.jar staging
        
      - name: Step 4 - Persist workflow data as artifacts
        uses: actions/upload-artifact@v2
        with:
         name: github-actions-artifact
         path: staging
