name: Java build with ant

on:
  push:
    branches:
      - GitHub_Action_Testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from Github
        uses: actions/checkout@v2
      
      - name: Step 2 - copying the files
        run: pwd && whoami && ls -l
